{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "67d0febd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "1. All students\n",
      "---------------\n",
      "(1, 'Aarav', 20, 'Pune')\n",
      "(2, 'Meera', 21, 'Mumbai')\n",
      "(3, 'Kabir', 22, 'Delhi')\n",
      "(4, 'Anaya', 20, 'Pune')\n",
      "\n",
      "2. Students from Pune\n",
      "---------------------\n",
      "('Aarav', 'Pune')\n",
      "('Anaya', 'Pune')\n",
      "\n",
      "3. Students ordered by age\n",
      "--------------------------\n",
      "('Kabir', 22)\n",
      "('Meera', 21)\n",
      "('Aarav', 20)\n",
      "('Anaya', 20)\n",
      "\n",
      "4. Join students with courses\n",
      "-----------------------------\n",
      "('Aarav', 'Python', 5000)\n",
      "('Anaya', 'Python', 5000)\n",
      "('Kabir', 'Data Science', 8000)\n",
      "('Meera', 'SQL', 3500)\n",
      "('Meera', 'Python', 5000)\n",
      "\n",
      "5. Course-wise enrollment count\n",
      "-------------------------------\n",
      "('Python', 3)\n",
      "('SQL', 1)\n",
      "('Data Science', 1)\n",
      "\n",
      "6. After update - students\n",
      "--------------------------\n",
      "(1, 'Aarav', 20, 'Pune')\n",
      "(2, 'Meera', 21, 'Bengaluru')\n",
      "(3, 'Kabir', 22, 'Delhi')\n",
      "(4, 'Anaya', 20, 'Pune')\n",
      "\n",
      "7. After update - courses\n",
      "-------------------------\n",
      "(101, 'Python', 5500)\n",
      "(102, 'SQL', 3500)\n",
      "(103, 'Data Science', 8000)\n",
      "\n",
      "8. After delete - students\n",
      "--------------------------\n",
      "(1, 'Aarav', 20, 'Pune')\n",
      "(2, 'Meera', 21, 'Bengaluru')\n",
      "(4, 'Anaya', 20, 'Pune')\n",
      "\n",
      "9. After delete - enrollments\n",
      "-----------------------------\n",
      "(1, 1, 101, '2026-05-23')\n",
      "(2, 2, 102, '2026-05-23')\n",
      "(3, 3, 103, '2026-05-23')\n",
      "(4, 4, 101, '2026-05-23')\n",
      "\n",
      "Database saved to: D:\\DUSHYANT CODING WORLD\\Internship\\Assignment\\Assig-5\\sqlite_practice.db\n"
     ]
    }
   ],
   "source": [
    "import sqlite3\n",
    "from pathlib import Path\n",
    "\n",
    "# Create or open a local SQLite database file.\n",
    "db_path = Path(\"sqlite_practice.db\")\n",
    "conn = sqlite3.connect(db_path)\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# Start fresh so the cell is safe to run multiple times.\n",
    "cursor.execute(\"DROP TABLE IF EXISTS enrollments\")\n",
    "cursor.execute(\"DROP TABLE IF EXISTS students\")\n",
    "cursor.execute(\"DROP TABLE IF EXISTS courses\")\n",
    "\n",
    "# Create 3 related tables.\n",
    "cursor.execute(\"\"\"\n",
    "CREATE TABLE students (\n",
    "    student_id INTEGER PRIMARY KEY,\n",
    "    student_name TEXT NOT NULL,\n",
    "    age INTEGER,\n",
    "    city TEXT\n",
    ")\n",
    "\"\"\")\n",
    "\n",
    "cursor.execute(\"\"\"\n",
    "CREATE TABLE courses (\n",
    "    course_id INTEGER PRIMARY KEY,\n",
    "    course_name TEXT NOT NULL,\n",
    "    fee INTEGER NOT NULL\n",
    ")\n",
    "\"\"\")\n",
    "\n",
    "cursor.execute(\"\"\"\n",
    "CREATE TABLE enrollments (\n",
    "    enrollment_id INTEGER PRIMARY KEY,\n",
    "    student_id INTEGER NOT NULL,\n",
    "    course_id INTEGER NOT NULL,\n",
    "    enrolled_on TEXT DEFAULT CURRENT_DATE,\n",
    "    FOREIGN KEY (student_id) REFERENCES students(student_id),\n",
    "    FOREIGN KEY (course_id) REFERENCES courses(course_id)\n",
    ")\n",
    "\"\"\")\n",
    "\n",
    "# Insert sample records.\n",
    "students = [\n",
    "    (1, \"Aarav\", 20, \"Pune\"),\n",
    "    (2, \"Meera\", 21, \"Mumbai\"),\n",
    "    (3, \"Kabir\", 22, \"Delhi\"),\n",
    "    (4, \"Anaya\", 20, \"Pune\"),\n",
    "]\n",
    "\n",
    "courses = [\n",
    "    (101, \"Python\", 5000),\n",
    "    (102, \"SQL\", 3500),\n",
    "    (103, \"Data Science\", 8000),\n",
    "]\n",
    "\n",
    "enrollments = [\n",
    "    (1, 1, 101),\n",
    "    (2, 2, 102),\n",
    "    (3, 3, 103),\n",
    "    (4, 4, 101),\n",
    "    (5, 2, 101),\n",
    "]\n",
    "\n",
    "cursor.executemany(\"INSERT INTO students VALUES (?, ?, ?, ?)\", students)\n",
    "cursor.executemany(\"INSERT INTO courses VALUES (?, ?, ?)\", courses)\n",
    "cursor.executemany(\"INSERT INTO enrollments (enrollment_id, student_id, course_id) VALUES (?, ?, ?)\", enrollments)\n",
    "conn.commit()\n",
    "\n",
    "# Helper to display query results clearly.\n",
    "def show_query(title, query, params=()):\n",
    "    print(f\"\\n{title}\")\n",
    "    print(\"-\" * len(title))\n",
    "    rows = cursor.execute(query, params).fetchall()\n",
    "    for row in rows:\n",
    "        print(row)\n",
    "\n",
    "# Different SELECT operations.\n",
    "show_query(\"1. All students\", \"SELECT * FROM students\")\n",
    "show_query(\"2. Students from Pune\", \"SELECT student_name, city FROM students WHERE city = ?\", (\"Pune\",))\n",
    "show_query(\"3. Students ordered by age\", \"SELECT student_name, age FROM students ORDER BY age DESC\")\n",
    "show_query(\n",
    "    \"4. Join students with courses\",\n",
    "    \"\"\"\n",
    "    SELECT s.student_name, c.course_name, c.fee\n",
    "    FROM enrollments e\n",
    "    JOIN students s ON e.student_id = s.student_id\n",
    "    JOIN courses c ON e.course_id = c.course_id\n",
    "    ORDER BY s.student_name\n",
    "    \"\"\",\n",
    ")\n",
    "show_query(\n",
    "    \"5. Course-wise enrollment count\",\n",
    "    \"\"\"\n",
    "    SELECT c.course_name, COUNT(*) AS total_students\n",
    "    FROM enrollments e\n",
    "    JOIN courses c ON e.course_id = c.course_id\n",
    "    GROUP BY c.course_name\n",
    "    ORDER BY total_students DESC\n",
    "    \"\"\",\n",
    ")\n",
    "\n",
    "# Update some data.\n",
    "cursor.execute(\"UPDATE students SET city = ? WHERE student_name = ?\", (\"Bengaluru\", \"Meera\"))\n",
    "cursor.execute(\"UPDATE courses SET fee = fee + 500 WHERE course_name = ?\", (\"Python\",))\n",
    "conn.commit()\n",
    "\n",
    "show_query(\"6. After update - students\", \"SELECT * FROM students\")\n",
    "show_query(\"7. After update - courses\", \"SELECT * FROM courses\")\n",
    "\n",
    "# Delete some data.\n",
    "cursor.execute(\"DELETE FROM enrollments WHERE student_id = ? AND course_id = ?\", (2, 101))\n",
    "cursor.execute(\"DELETE FROM students WHERE student_name = ?\", (\"Kabir\",))\n",
    "conn.commit()\n",
    "\n",
    "show_query(\"8. After delete - students\", \"SELECT * FROM students\")\n",
    "show_query(\"9. After delete - enrollments\", \"SELECT * FROM enrollments\")\n",
    "\n",
    "conn.close()\n",
    "print(f\"\\nDatabase saved to: {db_path.resolve()}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
